apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      database: telegraf
      user: 'root'
      url: http://influxdb.influxdb.svc:8086
      jsonData:
        timeInterval: "10s"
      secureJsonData:
        password: root