apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  install:
    createNamespace: true
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # admin:
    #   existingSecret: grafana-credentials
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
      notifiers:
        enabled: true
        label: grafana_notifiers