apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: telegraf-env
  namespace: influxdb
  envs:
  - ./secrets/telegraf.env
- name: influxdb-auth
  namespace: influxdb
  envs:
  - ./secrets/influxdb.env
- name: grafana-credentials
  namespace: monitoring
  envs:
  - ./secrets/grafana.env
- name: grafana-notifiers
  namespace: monitoring
  files:
  - ./secrets/.notifiers-secret.yaml
- name: grafana-datasources
  namespace: monitoring
  files:
  - ./secrets/grafana-datasources.yaml
- name: google-credentials
  namespace: kube-system
  envs:
  - ./secrets/google.env
- name: minecraft-creds
  namespace: minecraft
  envs:
  - ./secrets/minecraft.env
- name: wioc02
  namespace: wioc02
  files:
  - ./secrets/wioC02.env
- name: wiotemphu
  namespace: wiotemp1
  files:
  - ./secrets/wiotemp1.env
- name: wikileet-api
  namespace: wikileet-test
  envs:
  - ./secrets/wikileet-api.env
- name: wikileet-api
  namespace: wikileet-dev
  envs:
  - ./secrets/wikileet-api.env
- name: wikileet-api
  namespace: wikileet
  envs:
  - ./secrets/wikileet-api.env
- name: external-dns
  namespace: externaldns
  envs:
  - ./secrets/external-dns.env
generatorOptions:
  disableNameSuffixHash: true
patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-notifiers
      namespace: monitoring
      labels:
        "grafana_notifiers": "true"
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-datasources
      namespace: monitoring
      labels:
        grafana_datasource: "1"
