apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mqtt
spec:
  endpoints:
  - dnsName: mqtt.leetserve.com
    recordTTL: 180
    recordType: A
    targets:
    - 96.228.17.74
