#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: kube-system
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: thomseddon/traefik-forward-auth:2-arm
          name: traefik-forward-auth
          args:
            - --log-level=debug
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            - name: DOMAIN
              value: "api.wikileet.leetserve.com"
            # INSECURE_COOKIE is required unless using https entrypoint
            - name: INSECURE_COOKIE
              value: "true"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-credentials
                  key: clientId
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-credentials
                  key: secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: google-credentials
                  key: nonce
            - name: WHITELIST
              value: gabeduke@gmail.com,zepterfd@gmail.com,rachellison214@gmail.com,antoniafd@gmail.com,john.k.duke@gmail.com,darienduke@gmail.com,jonathanvassar@gmail.com,oconn2sh@gmail.com,jodyksanchez@gmail.com,skipjody@gmail.com,Cocadukes1@gmail.com,gladysmduke@gmail.com,elise.duke45@gmail.com

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: kube-system
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
    - name: auth-http
      port: 4181
      targetPort: 4181

---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: http://traefik-forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
