apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gift-wiki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wikileet
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gabeduke/django-gift-wiki
    path: deploy/prod
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

