apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- cert-manager.yaml
- external-dns.yaml
# - grafana.yaml
- influxdb.yaml
- minecraft.yaml
- mosquitto.yaml
- prom-stack.yaml
- reap.yaml
