apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://itzg.github.io/minecraft-server-charts/"
    chart: minecraft
    targetRevision: "4.7.4"
    helm:
      values: |-
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 6Gi
            cpu: 3
        nodeSelector:
          kubernetes.io/hostname: mothership
        tolerations:
          - key: "node-role.leetserve.com/mothership"
            operator: "Exists"
            effect: "NoSchedule"
        livenessProbe:
          initialDelaySeconds: 120
        readinessProbe:
          initialDelaySeconds: 120
        minecraftServer:
          eula: "true"
          whitelist: false
          ops: deadful_grate,3HandedKing,LogCabinCrew,3HandsKing3626
          memory: 6144M
          serviceType: LoadBalancer
          overrideServerProperties: true
          motd: "Welcome to Casimir's LeetServe Minecraft Server!"
          rcon:
            enabled: true
            port: 25575
            existingSecret: minecraft-creds
            secretKey: RCON_PASSWORD
            serviceType: LoadBalancer

        persistence:
          storageClass: "longhorn"
          dataDir:
            enabled: true

        serviceAnnotations:
          external-dns.alpha.kubernetes.io/hostname: minecraft.leetserve.com

        mcbackup:
          enabled: true
          persistence:
            storageClass: "longhorn"
            backupDir:
              enabled: true

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
