apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  destination:
    namespace: mosquitto
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mosquitto
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 4.4.0
    helm:
      values: |-
        service:
          main:
            type:
              LoadBalancer
            annotations:
              external-dns.alpha.kubernetes.io/hostname: mqtt.leetserve.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
