apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikileet-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wikileet
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gabeduke/wikileet-api
    path: deploy/wikileet
    targetRevision: HEAD
    helm:
      releaseName: wikileet
      values: |-
        ingress:
          ingressClassName: traefik
          annotations:
            "external-dns.alpha.kubernetes.io/hostname": "wikileet.leetserve.com"
            kubernetes.io/ingress.class: traefik
            ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,kube-system-traefik-forward-auth@kubernetescrd
          hosts:
          - host: wikileet.leetserve.com
            paths:
            - path: /
              pathType: ImplementationSpecific
          tls:
          - secretName: wikileet-tls
            hosts:
              - wikileet.leetserve.com
        configmapValues:
          CFG_DATABASE_NAME: "production"
      parameters:
      - name: image.tag
        value: $ARGOCD_APP_REVISION

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
