apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wioc02
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wioc02
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gabeduke/wioC02Logger
    path: deploy/
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
