apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: flux-system
spec:
  interval: 5m
  install:
    createNamespace: true
  targetNamespace: influxdb
  chart:
    spec:
      chart: influxdb
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: 1.8.9
    persistence:
      enabled: false
    env:
      - name: INFLUXDB_DB
        value: telegraf