apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/deploy/longhorn.yaml

patches:
  - path: patch-manager-tolerations.yaml
    target: 
      kind: DaemonSet
  - path: patch-driver-tolerations.yaml
    target: 
      kind: Deployment
  - path: patch-ui-tolerations.yaml
    target: 
      kind: Deployment
