apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eqmx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eqmx
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://repos.emqx.io/charts
    chart: emqx
    targetRevision: "4.3.8"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true