apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hivemq
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hivemq
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://hivemq.github.io/helm-charts
    chart: hivemq
    targetRevision: "0.9.2"
    # helm:
    #   values: |-
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true