apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
configMapGenerator:
  - name: grafana-dashboards
    files:
      - data/dashboard-iot.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
resources:
  - data/datasource-influxdb.yaml