---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: influxdb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/influxdb
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  validation: client

