apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-data
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.homelab }}
    path: apps/grafana-data
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
