apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: externaldns
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: "6.6.1"
    helm:
      values: |-
        crd:  
          create: true
        image:
          registry: k8s.gcr.io
          repository: external-dns/external-dns
          tag: v0.12.0
        provider: aws
        sources:
          - service
          - ingress
          - crd
        aws:
          credentials:
            secretName: external-dns
          region: us-east-1
          zoneType: public
        domainFilters:
          - leetserve.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
