apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: externaldns
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: "6.6.1"
    helm:
      values: |-
        crd:  
          create: true
        image:
          registry: docker.io
          repository: dukeman/external-dns
          tag: v0.13.2-crd-anno
        provider: aws
        sources:
          - ingress
          - crd
        aws:
          credentials:
            accessKeyIDSecretRef:
              name: external-dns
              key: aws_secret_access_key
            secretAccessKeySecretRef:
              name: external-dns
              key: aws_access_key_id
          region: us-east-1
          zoneType: public
        domainFilters:
          - leetserve.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
