apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "6.32.9"
    helm:
      values: |-
        admin:
          existingSecret: grafana-credentials
        sidecar:
          datasources:
            enabled: true
            label: grafana_datasource
            searchNamespace: ALL
          dashboards:
            enabled: true
            label: grafana_dashboard
            searchNamespace: ALL
          notifiers:
            enabled: true
            label: grafana_notifiers
            searchNamespace: ALL
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: grafana.leetserve.com
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
          - grafana.leetserve.com
          - localhost
          tls:
          - hosts:
            - grafana.leetserve.com
            secretName: grafana-tls
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
