apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikileet-api-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wikileet-dev
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/gabeduke/wikileet-api
    path: deploy/wikileet
    targetRevision: develop
    helm:
      releaseName: $ARGOCD_APP_NAME
      values: |-
        image:
          tag: $ARGOCD_APP_SOURCE_TARGET_REVISION
        ingress:
          annotations:
            "external-dns.alpha.kubernetes.io/hostname": "dev.wikileet.leetserve.com"
          hosts:
          - host: dev.wikileet.leetserve.com
          tls:
          - secretName: wikileet-tls
            hosts:
              - dev.wikileet.leetserve.com
        configmapValues:
          CFG_DATABASE_NAME: "develop"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
